// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVa8sk7NYKOp0ZSVkRTeC_duPbeep931o',
    appId: '1:674682531029:web:40953eeaf6ad0f10ebc65c',
    messagingSenderId: '674682531029',
    projectId: 'mynotes-hopefully-test',
    authDomain: 'mynotes-hopefully-test.firebaseapp.com',
    storageBucket: 'mynotes-hopefully-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIKgCIn02Bg0u5dxGq7wEaGzvwJxZuHkA',
    appId: '1:674682531029:android:6e556583b35f849eebc65c',
    messagingSenderId: '674682531029',
    projectId: 'mynotes-hopefully-test',
    storageBucket: 'mynotes-hopefully-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACdKs-ESP1LN4tQdyzGEGKjcMUtrExjOo',
    appId: '1:674682531029:ios:d390e5cd6db37998ebc65c',
    messagingSenderId: '674682531029',
    projectId: 'mynotes-hopefully-test',
    storageBucket: 'mynotes-hopefully-test.appspot.com',
    iosClientId: '674682531029-934i7qhb2scbrrpavd4jrmuj3aadcn8p.apps.googleusercontent.com',
    iosBundleId: 'com.test.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACdKs-ESP1LN4tQdyzGEGKjcMUtrExjOo',
    appId: '1:674682531029:ios:4d8cc9947fd008dfebc65c',
    messagingSenderId: '674682531029',
    projectId: 'mynotes-hopefully-test',
    storageBucket: 'mynotes-hopefully-test.appspot.com',
    iosClientId: '674682531029-ihe5i07fgme06gf4e2ojgjh3egll8t89.apps.googleusercontent.com',
    iosBundleId: 'com.test.mynotes.RunnerTests',
  );
}
